#!/bin/bash
##############
###Configs####
##############
###List of exfil usernames (default exfil)
exfil_user="hawks1 hawks2 hawks3 hawks4"
###File to search (default Exfil.log)
file=Exfil.log
#################
###End Configs###
#################

####################
# Start: Functions #
####################
fn_get_home_dir() {
  getent passwd $1 | cut -d: -f6
}
##################
# End: Functions #
##################

for i in ${exfil_user}; do
	exfil_user_home=$(fn_get_home_dir ${i})
        echo "Exfil User: " ${i}
        echo "Joins: " `grep -c "Join succeeded" ${exfil_user_home}/exfil-dedicated/Exfil/Saved/Logs/${file}`
	echo "Adds:  " `grep -c "Adding user" ${exfil_user_home}/exfil-dedicated/Exfil/Saved/Logs/${file}`
	echo "Close: " `grep -c "Closing channel" ${exfil_user_home}/exfil-dedicated/Exfil/Saved/Logs/${file}`
        echo ""
done

